### ISSUE TITLE
Add notifications of creation of new runs to slack

### ISSUE THREAD

**Issue by tsukasa-au** [SilverMaddy/ncss-coffeerun#2]
It would be awesome if coffeebot could notify the slack channel when a new run is created.

**Comment by tsukasa-au** [comment]
The interesting question here is how to go about implementing that. Three ideas:
  1. Have the webapp post a message to a queue somewhere (celery?), then subscribe to that in the bot
  2. Have the coffeebot poll the database for new open runs
  3. Have the webapp directly call into the slack api to post a new message to the channel.

The above are in preference order (I think a message bus between components is best, with the webapp directly knowing about and talking slack being the worst).

**Comment by SilverMaddy** [comment]
There's already the majority of a Celery integration. It isn't running at the moment, since it hasn't been needed, but it won't be as much work to bring it up and extend it to the subscription model.

**Comment by katharosada** [comment]
The reason I haven't implemented it yet is because I hadn't decided on
which one is the way to go. Either way, I think it should probably hook
into the existing events stuff which is used for email notifications and
the like.

**Comment by tsukasa-au** [comment]
This was implemented by @katharosada in 2bee8bdb762d5e9d0f2c9634cd2fdc6a706721de.
